print("              CV")
print("")
print("     Informaţii personale")
print("")
print("Nume/Prenume: Ştirbu Loredana")
print("Adresa: Bulgara 84")
print("Telefon: 060521300")
print("E-mail: stirbu.loretta@gmail.com")
print("Naţionalitate: moldoveancă")
print("Data nasşterii: 14.02.2005")
print("Sex: femenin")
print("")
print("     Educaţie şi formare")
print("")
print("Perioada: 2011-2020")
print("Diploma obţinută: atestat cl.9")
print("Numele şi tipul instituţiei de învăţământ: I.P.L.T.'Mihai Eminescu'")
print("")
print("     Competenţe şi abilităţi sociale")
print("")
print("Hobby: cititul cărţilor,relaxarea prin plimbări de seară şi ascultatul muzicii")
print("Competenţe şi aptitudini de utilizare a calculatorului: cunoştinţe de bază")
print("Permis de conducere: lipseşte")